[project]
name = "ai-travel-planner"
version = "0.1.0"
description = "AI-powered travel planner"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


