import streamlit as st
import requests
import datetime

BASE_URL = "http://localhost:8000"  # Replace with your actual API URL

# ================== UI STYLING BLOCK ==================
st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@500;700&display=swap');

html, body, [class*="css"] {
    font-family: 'Outfit', sans-serif;
    background-color: #0f1117;
    color: #f5f6fa;
}

.big-header {
    font-size: 3em;
    font-weight: 800;
    text-align: center;
    background: linear-gradient(90deg, #00ffe7, #63a4ff);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-bottom: 0.2em;
}

.sub-header {
    text-align: center;
    font-size: 1.2em;
    color: #d0d0d0;
    margin-bottom: 2em;
}

.stTextInput>div>div>input {
    background-color: #1e2128;
    color: white;
    border: 1px solid #444 !important;
    border-radius: 8px;
    padding: 10px;
}

button[kind="primary"] {
    background: linear-gradient(to right, #4e54c8, #8f94fb);
    color: white;
    border: none;
    border-radius: 8px;
    padding: 0.6em 1.5em;
    font-size: 1em;
    transition: 0.2s ease-in-out;
}

button[kind="primary"]:hover {
    background: linear-gradient(to right, #3e45b8, #6f74e4);
}

.markdown-body {
    background-color: #1b1d23;
    color: #f1f1f1;
    padding: 2em;
    border-radius: 12px;
    margin-top: 1.5em;
    box-shadow: 0 0 12px rgba(0, 255, 200, 0.05);
}

.markdown-body h1, .markdown-body h2 {
    color: #63a4ff;
}
</style>
""", unsafe_allow_html=True)



st.markdown("<div class='big-header'>🌍 Travel Planner Agentic Application</div>", unsafe_allow_html=True)
st.markdown("<div class='sub-header'>How can I help you in planning a trip? Let me know where do you want to visit.</div>", unsafe_allow_html=True)



# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []


with st.form(key="Query_form", clear_on_submit=True):
    user_input = st.text_input("User input", placeholder="e.g. Plan a trip to Kunnur for 5 days")
    submit_button = st.form_submit_button("send")


if submit_button and user_input.strip():
    try:
        with st.spinner("I am doing your trip planning ... "):
            payloads = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payloads)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# 🧭 AI Travel Plan

**🗓️ Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**👤 Created by:** Subhransu's Travel Agent

---

{answer}

---

🛈 *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""
            st.markdown(f"<div class='markdown-body'>{markdown_content}</div>", unsafe_allow_html=True)
        else:
            st.error("Bot failed to respond: " + response.text)

    except Exception as e:
        st.error(f"The response failed due to: {e}")
